### ISSUE TITLE
SPIKE-1: Indoor View Setup

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/SOEN390#21]
As a developer, I want an indoor view so that other developers can work on top of the separate view.

SAME VIEW UNCERTAINTIES:
* having an overlay over Google Maps (through SVG using polygons and lines) --> how do we translate the coords of SVG to coords of real life?
* "How do we toggle floors?" --> https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md
* Can we hide/display markers per floor?

SEPARATE VIEW UNCERTAINTIES:
* If separate view, can we implement all the same as above?
* Can we use locationServices onto a separate view?
* Will we have better control over indoor view/floor toggle?

TRANSITION UNCERTAINTIES:
* How do we translate indoor view to outdoor view, and vice-versa?
* How to hide markers based on zoom level in same view?

Please note down findings and feasibility checks.

**Comment by RGPosadas** [comment]
Please coordinate on who researches what

**Comment by cindyslittleplanet** [comment]
**TRANSITION UNCERTAINTIES:**

- How do we translate indoor view to outdoor view, and vice-versa?
In brief, not much was found.
However, as a non-seamless idea from indoor view to outdoor view (and vice-versa), for example, if an user inputs an outside starting point and inputs a classroom number as an destination point, then first give the directions from the outside starting point to the building containing the classroom. When the user gets close enough to the destination building, ask the user if they want to switch to the indoor view. If yes, then change to the indoor view of the building and show directions from entrance/lobby of the building to the destination classroom. 

- How to hide markers based on zoom level in same view?
Possible solution: Classify the markers by a certain zoom level (for it to appear), then create a function where it will show/hide based on whether the zoom level has reached the markers' classification. 
Alternative option: Cluster the markers, so that the map looks less messy, by showing the numbers of markers when zoomed out, and showing the individual markers only when zoomed in enough.

**Comment by cristian-aldea** [comment]
> having an overlay over Google Maps (through SVG using polygons and lines) --> how do we translate the coords of SVG to coords of real life?

Found a possible solution to this. We can covert the SVG to geojson and then again convert the geojson coordinate to fit the building size and location

**Comment by RGPosadas** [comment]
SPIKE REVIEW REPORT

SAME VIEW UNCERTAINTIES:
* Q1: having an overlay over Google Maps (through SVG using polygons and lines) --> how do we translate the coords of SVG to coords of real life? 
* A1: We were able to make SVG part of map, as for coordinates, can be handled as well
* Q2: "How do we toggle floors?" --> https://github.com/react-native-community/react-native-* maps/blob/master/docs/mapview.md
* A2: Not 100% sure yet, it should, however it's not working the map
* Q3: Can we hide/display markers per floor?
* A3: Yes, we can 

SEPARATE VIEW UNCERTAINTIES:
* Q1: Having an overlay over Google Maps (through SVG using polygons and lines) --> how do we translate the coords of SVG to coords of real life?
* A1: Yes, on a separate view. Horizontal + vertical view available. No pinch and zoom, but found some libraries to enable that.
* Q2: "How do we toggle floors?" --> https://github.com/react-native-community/react-native-* maps/blob/master/docs/mapview.md
* A2: Same thing as same view
* Q3: Can we hide/display markers per floor?
* A3: Yes, we can
* Q4: Can we use locationServices onto a separate view?
* A4: We can buy `beacons`, relatively cheap, other than buying hardware, it won't be possible. Indoor routing is possible, but we won't have the person's exact location on the map. https://stackoverflow.com/questions/29130244/svg-vector-map-indoor-navigational-routing/42742026

TRANSITION UNCERTAINTIES:
See Cindy's reply: https://github.com/RGPosadas/WayFinder/issues/21#issuecomment-591823843

**Comment by RGPosadas** [comment]
CONCLUSION:

Properly de-risked SAME VIEW with a blank project implementation.
De-risked all concerns, slight concern left for mapping SVGs.

Therefore, we are going for SAME VIEW implementation.

Good job team!
